title:   Elvis Liang
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Business System Analyst (BSA) based in Toronto, responsible for both BSA and data analytic tasks, experience in the software (gaming) industry.
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/elvisliang/About-Me-Elvis-Liang-3f4f047d65c5438a8d70686f9e849254">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
